# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bikes')),
            ],
        ),
        migrations.CreateModel(
            name='stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='rentals',
            name='end_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_station', to='bikes.stations'),
        ),
        migrations.AddField(
            model_name='rentals',
            name='start_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_station', to='bikes.stations'),
        ),
        migrations.AddField(
            model_name='rentals',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.users'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.stations'),
        ),
    ]
