# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20160605_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bikes',
            new_name='bike',
        ),
        migrations.RenameModel(
            old_name='rentals',
            new_name='rental',
        ),
        migrations.RenameModel(
            old_name='stations',
            new_name='station',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
