# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_auto_20160605_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='working',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
