# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_station_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
