# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_auto_20160605_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='rented',
        ),
        migrations.AddField(
            model_name='bike',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='bikes.rental'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.station'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='bikes.bike'),
        ),
    ]
