# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_auto_20160605_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_station', to='bikes.station'),
        ),
    ]
