# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_auto_20160610_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_debt',
            field=models.BooleanField(default=False),
        ),
    ]
