# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0011_rental_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
